---
- name: Create Gitea Pod
  containers.podman.podman_pod:
    name: '{{ gitea_hostname }}-pod'
    network: '{{ gitea_pod_network }}'
    ip: '{{ gitea_pod_ip }}'
    hostname: '{{ gitea_hostname }}.{{ gitea_domain }}'
    state: started

- name: Create Gitea Container Volume
  containers.podman.podman_volume:
    name: '{{ gitea_hostname }}-volume'
    state: present

- name: Create gitea Systemd Unit File
  ansible.builtin.template:
    src: container-gitea.service.j2
    dest: '/etc/systemd/system/container-{{ gitea_hostname }}.service'
    owner: root
    group: root
    mode: '0644'
  notify:
    - daemon-reload
    - restart gitea

- name: Create Nginx Container Volume
  containers.podman.podman_volume:
    name: '{{ gitea_hostname }}-nginx-vol'
    state: present

- name: Get Nginx Container Volume Info
  containers.podman.podman_volume_info:
    name: '{{ gitea_hostname }}-nginx-vol'
  register: volume_info

- name: Set Mountpoint
  ansible.builtin.set_fact:
    nginx_mountpoint: "{{ volume_info | community.general.json_query('volumes[0].Mountpoint') }}"

- name: Create Nginx Config File
  ansible.builtin.template:
    src: gitea-proxy.conf.j2
    dest: '{{ nginx_mountpoint }}/gitea-proxy.conf'
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart nginx

- name: Create Nginx Systemd Unit File
  ansible.builtin.template:
    src: container-nginx.service.j2
    dest: '/etc/systemd/system/container-{{ gitea_hostname }}-nginx.service'
    owner: root
    group: root
    mode: '0644'
  notify:
    - daemon-reload
    - restart nginx