---
- name: Create Jellyfin Pod
  containers.podman.podman_pod:
    name: '{{ jellyfin_hostname }}-pod'
    network: '{{ jellyfin_podman_network }}'
    ip: '{{ jellyfin_pod_ip }}'
    hostname: '{{ jellyfin_hostname }}.{{ jellyfin_domain }}'
    state: started

- name: Create Jellyfin Systemd Unit File
  ansible.builtin.template:
    src: container-jellyfin.service.j2
    dest: '/etc/systemd/system/container-{{ jellyfin_hostname }}.service'
    owner: root
    group: root
    mode: '0644'
  notify:
    - daemon-reload
    - restart jellyfin

- name: Create Nginx Container Volume
  containers.podman.podman_volume:
    name: '{{ jellyfin_hostname }}-nginx-vol'
    state: present

- name: Get Nginx Container Volume Info
  containers.podman.podman_volume_info:
    name: '{{ jellyfin_hostname }}-nginx-vol'
  register: volume_info

- name: Set Mountpoint
  ansible.builtin.set_fact:
    nginx_mountpoint: "{{ volume_info | community.general.json_query('volumes[0].Mountpoint') }}"

- name: Create Nginx Config File
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: '{{ nginx_mountpoint }}/nginx.conf'
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart nginx

- name: Create Nginx Systemd Unit File
  ansible.builtin.template:
    src: container-nginx.service.j2
    dest: '/etc/systemd/system/container-{{ jellyfin_hostname }}-nginx.service'
    owner: root
    group: root
    mode: '0644'
  notify:
    - daemon-reload
    - restart nginx