---
- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart gitea
  ansible.builtin.systemd:
    name: 'container-{{ gitea_hostname }}.service'
    state: restarted
    enabled: yes

- name: restart nginx
  ansible.builtin.systemd:
    name: container-{{ gitea_hostname }}-nginx.service
    state: restarted
    enabled: yes
